services:
  db:
    image: mongo
    restart: always
    env_file: "env"
    networks:
      - backend
  mongo_express:
    image: mongo-express
    env_file: "env"
    networks:
      - backend
      - frontend
    ports:
      - 8081:8081
    depends_on:
      - db
  mern:
    build: ./mern/
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000
    env_file: "env"


networks:
  frontend:
  backend:
