services:
  db:
    image: mongo
    restart: always
    env_file: "env"
    networks:
      - backend
  mongo_express:
    image: mongo-express
    env_file: "env"
    networks:
      - backend
      - frontend
    ports:
      - 8081:8081
    depends_on:
      - db


networks:
  frontend:
  backend:
