worker_processes 2;
events {
       worker_connections 2000;
}

http{

	upstream mern {
		 server mern:3000;

	}

	server {
	       listen 80;
	       location / {
	       		proxy_pass http://mern;
		}

	}
}